stages:
  - staging
  - production

deploy_staging:
  stage: staging
  pre-script:
  - npm --prefix ./apps/registry install
  - npm --prefix ./apps/registry run build

  script:
  - python3 -m venv virtualenv
  - virtualenv/bin/pip install -r requeriments.txt
  - virtualenv/bin/pip install uWSGI
  - virtualenv/bin/python manage.py migrate
  - virtualenv/bin/python manage.py collectstatic --noinput
  - touch /data/web/env_files/.env_mccannprove_stg
  - ln -s /data/web/env_files/.env_mccannprove_stg /data/web/stage/mccann-prove.emmanuellecode-base.com/mccann_prove/.env
  environment:
    name: staging
    url: https://mccann-prove.emmanuellecode-base.com

deploy_production:
  stage: production
  script:
  - python3 -m venv virtualenv
  - virtualenv/bin/pip install -r requeriments.txt
  - virtualenv/bin/pip install uWSGI
  - virtualenv/bin/python manage.py migrate
  - virtualenv/bin/python manage.py collectstatic --noinput
  - touch /data/web/env_files/.env_mccannprove
  - ln -s /data/web/env_files/.env_mccannprove /data/web/stage/mccann-prove.emmanuellecode.com/mccann_prove/.env
  environment:
    name: production
    url: https://mccann-prove.emmanuellecode.com