# Generated by Django 4.0.6 on 2022-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, verbose_name='FirstName')),
                ('lastname', models.CharField(max_length=25, verbose_name='LastName')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
                ('brand', models.CharField(max_length=25, verbose_name='LastName')),
                ('vehicle', models.CharField(max_length=25, verbose_name='LastName')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updates_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
